ARG BASE_IMAGE=carlomt/geant4

FROM $BASE_IMAGE AS builder

WORKDIR /workspace

ENV LANG=C.UTF-8
RUN ln -sf /usr/share/zoneinfo/UTC /etc/localtime
ENV DEBIAN_FRONTEND=noninteractive

RUN export DEBIAN_FRONTEND=noninteractive && \
    apt-get update && \
    apt-get -yq --no-install-recommends install \
    git \
    && \
    apt-get -y autoremove && \
    apt-get -y clean && \
    rm -rf /var/cache/apt/archives/* && \
    rm -rf /var/lib/apt/lists/*    

RUN cd /workspace && \
    git clone https://github.com/DCMTK/dcmtk.git && \
    # --branch tags/DCMTK-3.6.6 --single-branch && \ 
    cd dcmtk/ && \
    git checkout tags/DCMTK-3.6.6 && \
    mkdir build && \
    cd build && \
    cmake -G Ninja -DCMAKE_INSTALL_PREFIX=/opt/dcmtk \
    -DDCMTK_ENABLE_CXX11=ON \
    -DDCMTK_CXX11_FLAGS=-std=c++17 \
    -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
    ../ && \
    ninja install
    
#######################################################################

FROM $BASE_IMAGE

ENV LANG=C.UTF-8
RUN ln -sf /usr/share/zoneinfo/UTC /etc/localtime

COPY --from=builder /opt/dcmtk/ /opt/dcmtk/

ENTRYPOINT  ["/usr/bin/bash", "-l", "-c"]